version: 0.9.0.{build}
branches:
  only:
    - master
    - develop
    - release/*
    - feature/*
os: Windows Server 2012
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}.{build}"
  assembly_file_version: "{version}.{build}"
  assembly_informational_version: "{version}.{build}"
configuration:
  - Debug
  - Release
build:
  publish_nuget: true
  publish_nuget_symbols: true
