environment:
  CURRENT_VERSION: 0.9.0
version: 0.9.0-{build}
branches:
  only:
    - master
    - develop
    - release/*
    - feature/*
os: Windows Server 2012
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(CURRENT_VERSION).{build}"
  assembly_file_version: "$(CURRENT_VERSION).{build}"
  assembly_informational_version: "$(CURRENT_VERSION).{build}"
configuration:
  - Debug
  - Release
after_build:
  - nuget pack UmbracoVault/UmbracoVault.csproj -Symbols -Version %CURRENT_VERSION%-build%APPVEYOR_BUILD_NUMBER%
  - nuget pack UmbracoVault/UmbracoVault.csproj -Version %CURRENT_VERSION%
artifacts:
  - path: "*.nupkg"
